### ISSUE TITLE
Namespace to Gateway - `gwa namespace` to `gwa gateway`

### ISSUE THREAD

**Issue by rustyjux** [bcgov/gwa-cli#103]
As an API provider, I need consistent naming on the Portal, docs, and CLI, so I don't get confused 😵

Throughout the CLI, replace "namespace" with "gateway". In particular, the `gwa namespace` set of commands.

Definition of done:
- Portal, docs, and CLI all updated

**Comment by ikethecoder** [comment]
Think we need to include in DoD an "upgrade" to the v3 api automatically so that the user does not have to pass `--api-version=v3` to the command or modify any internal files to get things to work.

**Comment by rustyjux** [comment]
We don't need to do any of that. 

For testing: set your .env file to 
```
GWA_API_HOST=api-gov-bc-ca.dev.api.gov.bc.ca
GWA_CLIENT_ID=gwa-cli
GWA_VERSION=v3
CLI_VERSION=3.0.0-dev
```
(`GWA_API_HOST` will get over-ridden from `.gwa-config.yaml`, but this is the default used the first time if there is no `.gwa-config.yaml`)
and then instead of `gwa` use `just run`, e.g. `just run gateway create`

When building, `just release` uses env vars from .env locally or from the GHA.
@Elson9 FYI
