### ISSUE TITLE
Namespace to Gateway - `gwa gateway create`, gateway naming behaviour

### ISSUE THREAD

**Issue by rustyjux** [bcgov/gwa-cli#104]
As an API provider getting start with the Portal, I want to (be able to) set the display name for a new gateway, so that I can distinguish my gateways.

In addition to #103, some changes to the behaviour of `gwa gateway create` are needed.

Requirements:
- rename:
  -  -n --name to -i --gateway-id
  - -d -description to --display-name (-d)

- default behaviour (without the -g flag):
  - autogenerate gateway id
  - prompt user to set display name
    - default name `<IDIR>'s gateway`, accept (ENTER) or specify
    - default handling will be done by Keystone list, so don't need to worry about it here

- as before, use an optional flag (-g --generate) to create a gateway with a default display name. 

- preserve ability to specify gateway id alongside display name (useful for our tests, if not also for users)

- ensure all usages result in current gateway being set to the new gateway. This was not the case when using `gwa namespace create` without options.

**Comment by ikethecoder** [comment]
Verified - looks good
