### ISSUE TITLE
gwa info returns an error with in illformed URL

### ISSUE THREAD

**Issue by dkelsey** [bcgov/gwa-cli#30]
With no `.env` I'm guessing there is a default query URL that is used.  It is malformed and the query returns an error.
```bash
[app@alkaid:~]> gwa info
x Error Fetchrequest to https://authz-apps-gov-bc-ca..api.gov.bc.ca/auth/realms/aps/protocol/openid-connect/token failed, reason: getaddrinfo ENOTFOUND authz-apps-gov-bc-ca..api.gov.bc.ca
```
I'd expect that if the issue is that there is no `.env` then `info` would return a more meaningful message.

**Comment by Jonesy** [comment]
This will be fixed in 1.2, should be released soon.
