### ISSUE TITLE
Failing to publish gateway configuration in latest version (1.3.0)

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-cli#40]
When `gwa pg` is run, it always returns:

```
✓ Success Configuration undefined Published
```

Checking the `gwa-api` shows that the CLI never calls the api.

**Comment by NithinKuruba** [comment]
@ikethecoder I tried to replicate the issue but I could not. I was able to publish the config using latest version of gwa-cli.

**Comment by NithinKuruba** [comment]
Identified the issue and added a code fix. https://github.com/bcgov/gwa-cli/pull/41
