### ISSUE TITLE
Publishing empty config with a qualifier causes all config for the namespace to be deleted

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-cli#49]
**Summary**: If you intend to use a qualifier in the namespace tagging (i.e./ `ns.mynamespace.dev`) and its in a directory with no configuration, and you run `gwa pg`, the result is that all the namespace config is deleted.  Which is not the desired behaviour.  The expected behaviour is that all config for that qualifier is deleted.

**Solution**: Update `gwa pg` to have a `--qualifier <qualifier>` command parameter, which it will pass to the gwa api when publishing, to use as a select tag rather than deriving it from the config.

**Comment by Jonesy** [comment]
@ikethecoder do I just add `qualifier` to the `form-data` of the request body?

**Comment by chrsamp** [comment]
@Jonesy to close the ticket as this is resolved in latest gwa-cli
