### ISSUE TITLE
Command: `publish-gateway`

### ISSUE THREAD

**Issue by Jonesy** [bcgov/gwa-cli#52]
`publish-gateway` pushes a configuration file as well as the option to run the publish as a dry run to confirm the configuration file is configured correctly. It requires the following options

`--namespace` allows the user to assign a specific URL so they don't have to have a `.env` file located in the `cwd` to publish
`--dry-run` boolean

### Acceptance Criteria

- [x] `api.go` can handle different content types to PUT/POST requests
- [x] Function or pattern for uploading a file via `http.NewRequest` body
- [x] Unit tests

#### Bonus
Start with one config file but look into handling multiple configs if it still would be a useful feature for users.

**Comment by odyeung** [comment]
josh will reach out to niraj if ready!
