### ISSUE TITLE
Device Login

### ISSUE THREAD

**Issue by Jonesy** [bcgov/gwa-cli#54]
Allow users to sign into the API via device login instead of using client credentials to login. This allows then to use the CLI tool from any directory instead of ensuring they have an up-to-date `.env` config in their `cwd`.

### Acceptance Criteria

- [x] Printout the URL to sign in the device, as well as the one-time authenticator code
- [x] Poll for 1-2 minutes
- [x] Get the security schemes from the portal's `openapi.yaml`
- [x] Use the well-known configurations to extract the OIDC endpoints, so we don't have to emded them in the CLI
- [x] Add `client-id` and `client-secret` as an alternative to device login
- [x] Add global `host` command that lets us override the login the default API host.
- [x] Unit tests

**Comment by ikethecoder** [comment]
Feature branch details:

* Endpoint: https://api-services-portal-feature-gwa-cli-v2.apps.silver.devops.gov.bc.ca/ds/api
* The endpoint will have a "link" header in a standard format like: `</ds/api/v2/openapi.yaml>; rel="service-desc"`.  Take the link of the `service-desc` and get the OpenAPI spec
* OpenAPI spec: https://api-services-portal-feature-gwa-cli-v2.apps.silver.devops.gov.bc.ca/ds/api/v2/openapi.yaml
* Under `components/securitySchemes/openid/openIdConnectUrl` this will be the URL for the `.well-known/openid-configuration`

**Comment by ikethecoder** [comment]
Following RFC6749 (https://www.rfc-editor.org/rfc/rfc6749#section-4.4.3), the client credential login will not return a refresh token, so when the token expires, the user will either have to run `gwa login` again with the client id or secret, or the credentials could be stored in a local file under user's home directory.
