### ISSUE TITLE
GWA GET command throws error about invalid credentials even when correct credentials is set

### ISSUE THREAD

**Issue by nirajCITZ** [bcgov/gwa-cli#65]
Step 1 : Set valid token and namespace to gwa-config file
step 2: Upload/create product, dataset to the namespace
Step 3: Check output of 'gwa get dataset' or 'gwa get product'or any other gwa get command

Actual result : The command returns error about invalid credentials

Expected Result : The command should return details of dataset or products when valid correct is set
<img width="629" alt="Screenshot 2023-09-01 at 1 32 33 PM" src="https://github.com/bcgov/gwa-cli/assets/94716060/10d84b1b-477c-4ad8-972e-89e9ef3e4626">

**Comment by Jonesy** [comment]
Had a old pre-refactoring `RefreshToken` call. Fixed and closed.
