### ISSUE TITLE
`--host` not acknowledged using `login` command

### ISSUE THREAD

**Issue by Jonesy** [bcgov/gwa-cli#68]
Currently setting the global flag for `--host` doesn't update the URL when logging in.

Acceptance Criteria:
Using `$ gwa login --host my.site` is properly routed

**Comment by franTarkenton** [comment]
Hey Joshua... 

I'm trying to use the cli to login.  I used to populate a .env file using the old gwa cli tool and then subsequent gwa cli commands, I'm guessing would read the .env file and handle the authorization for me.

As attempt to pivot to the new tool (v2.0.4) I can't seem to get the login process working correctly.

What i've tried:

```
./gwa login

Error: Get "": unsupported protocol scheme ""
```
and

```
./gwa config set --namespace $GWA_NAMESPACE
./gwa login --client-id $GWA_CLIENTID --client-secret $GWA_TOKEN

Error: Get "": unsupported protocol scheme ""
```

Running on WSL/Ubuntu 22.04

Any ideas / suggestions?

**Comment by Jonesy** [comment]
Hey @franTarkenton, we're just in the process of a prod release that will enable these new features to work, it should be deployed soon, I'll follow up and let you know when it's ready. The 2.0.4 has been marked as a "Pre-release" in the meantime, so once it gets the official release stamp it should work.
