### ISSUE TITLE
Support multiple files for `pg` command

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-cli#73]
This is for backward compatibility with the previous version.

You would be able to do: gwa pg and it would gather up all the *.yaml files and send a YAML Multi-document file to the gwa api.

Something similar should be available in V2 of the CLI.

**Comment by Jonesy** [comment]
Just pushed a first pass at this feature for testing @nirajCITZ and @ikethecoder on `feature/multi-file-pg`

**Comment by Jonesy** [comment]
Added some validation, error messages and it'll publish the directory if there's no input defined. I think it won't be too hard to add multiple arguments too, ie `gwa pg config.yaml other-config.yaml directory_with_a_config/config.yaml` too if that sounds OK.

Was also curious if you'll foresee us needing to use any of these file processing features for when we publish to the gateway from the `apply` command @ikethecoder
