### ISSUE TITLE
Add inquirer module

### ISSUE THREAD

**Issue by Jonesy** [bcgov/gwa-cli#84]
Currently the only way to read user input is by command line arguments and flags (`--name="test"`), which while fine for small operations can be cumbersome for human input.

## Acceptance Criteria

Implement a library that generates multi-step prompts, right now https://github.com/charmbracelet/bubbletea seems to be the best, most regularly maintained option. Charm are well regarded in the Go CLI space, and we use their Lipgloss library for styling. Ideally would be implemented for the following commands:

- `apply`
- `generate-config`
- `namespace`
- `publish-gateway`
- `login` (maybe)

**Comment by ikethecoder** [comment]
Josh, looks good - can you make a small change and put the "client-credentials-shared-idp" template first in the list of templates.  And default a filename to "gw-config.yml".

**Comment by Jonesy** [comment]
Both are done and pushed @ikethecoder
