### ISSUE TITLE
`get` detailed output

### ISSUE THREAD

**Issue by Jonesy** [bcgov/gwa-cli#85]
Org Units are required to create a dataset, but users might not know the correct name of one off hand when they are creating a dataset.

## Acceptance Criteria

Add `org-units` argument to `gwa get` with the required flag of `--org` as a filter.

Example:

```shell
$ gwa get org-units --org ministry-of-citizens-services
```

**Comment by Jonesy** [comment]
@ikethecoder I think we just need to implement an endpoint for this URL if it hasn't been deployed yet.

**Comment by ikethecoder** [comment]
Example API call:
```
curl -X 'GET' \
  'https://api-gov-bc-ca.dev.api.gov.bc.ca/ds/api/v2/organizations/ministry-of-citizens-services' \
  -H 'accept: application/json'
```

Returns `orgUnits` which is an array of objects containing a `name` and `title`.  These can be displayed.

For json and yaml output, you can show the full response as in the future there may be more information added.

**Comment by ikethecoder** [comment]
Perhaps the call is more accurately:

```
gwa get organization--name ministry-of-citizens-services
```
