### ISSUE TITLE
"Gateway Services publish failed" message when using `gwa apply`

### ISSUE THREAD

**Issue by rustyjux** [bcgov/gwa-cli#99]
Even when only publishing a Product or DraftDataset, `gwa` makes a PUT call to `api.gov.bc.cagw/api/v2/namespaces/gw-abc123/gateway` which will return an error message:
![image](https://github.com/bcgov/gwa-cli/assets/38586679/ee0965db-fcf7-44bb-b229-72b37d11d215)

This is unnecessary and a nuisance for users.

**Comment by ikethecoder** [comment]
Verified - looks good

**Comment by rustyjux** [comment]
testing modified Jira automation - this should not change ticket status to In Progress
